trigger: none

pool:
  name: RPLocalPool


parameters:
  - name: targetEnvironment
    displayName: "Target Environment"
    type: string
    default: dev
    values:
      - dev
      - test

  - name: createInfra
    displayName: "Create Infra"
    type: boolean
    default: false


stages:
  - stage: InfraValidationStage
    variables:
      - template: /parameters/${{ parameters.targetEnvironment }}.variables.yaml
    displayName: 'Infra Validation Stage'
    jobs:
      - job: InfraValidationJob
        displayName: 'Infra Validation Job'
        steps:
        - checkout: self
          path: ./s
        - task: AzureCLI@2
          name: LintingBicep
          displayName: 'Linting Bicep'
          inputs:
            azureSubscription: ${{ variables.serviceConnection }}  
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: | 
              az bicep build --file templates/main.bicep
        - task: AzureCLI@2
          name: ValidatingBicep
          displayName: 'Validate Bicep'
          inputs:
            azureSubscription: ${{ variables.serviceConnection }}  
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: | 
              az deployment group validate \
                --resource-group $(resourceGroupName) \
                --template-file templates/main.bicep \
                --parameters parameters/${{ parameters.targetEnvironment }}.parameters.json
        - task: AzureCLI@2
          name: DryRun
          displayName: 'Dry Run'
          inputs:
            azureSubscription: ${{ variables.serviceConnection }}  
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: | 
              az deployment group what-if \
                --resource-group $(resourceGroupName) \
                --template-file templates/main.bicep \
                --parameters parameters/${{ parameters.targetEnvironment }}.parameters.json

  - stage: CreateInfraStage
    dependsOn: InfraValidationStage
    condition: and(succeeded(), eq('${{ parameters.createInfra }}', true))
    displayName: 'Create Infra Stage'    
    variables:
      - template: parameters/${{ parameters.targetEnvironment }}.variables.yaml
    jobs:
      - job: createInfraJob
        displayName: 'Create Infra Job'
        steps:
        - task: AzureCLI@2
          enabled: false
          name: CreateInfra
          displayName: 'Create Infra'
          inputs:
            azureSubscription: ${{ variables.serviceConnection }}  
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: | 
              az deployment group create \
                --resource-group $(resourceGroupName) \
                --template-file templates/main.bicep \
                --parameters parameters/${{ parameters.targetEnvironment }}.parameters.json